trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  azureSubscription: 'carlosvp'
  appName: 'BestBikeApp'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: | 
      python app.py
    displayName: 'Run Flask Application'

  - task:  PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)'
      artifactName: 'drop'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: $(azureSubscription)
      appType: 'webApp'
      WebAppName: $(appName)
      packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'